### ISSUE TITLE
Confusing documentation: '$$' sequence needed to make this work

### ISSUE THREAD

**Issue by tgoorden** [marhop/pandoc-unicode-math#13]
A bit of a minor issue, but what wasn't clear from the documentation was that you need to envelop any unicode characters with `$ <unicode goes here> $` before the plugin picks them up. Only after looking at the example file, did I realise the problem.

A suggestion would be to mention this in the Readme.

**Comment by marhop** [comment]
Agreed! I remember having run into this issue myself. :joy: I'll fix the README.
