### ISSUE TITLE
posix_spawnp: does not exist using the plugin with pandoc on nixos

### ISSUE THREAD

**Issue by YievCkim** [marhop/pandoc-unicode-math#14]
Hi,

I get this error when I try to run the plugin in nixos:

```
$ pandoc --from=markdown --to=pdf --filter pandoc-unicode-math -o test.pdf test.md 
Error running filter pandoc-unicode-math:
pandoc-unicode-math: createProcess: posix_spawnp: does not exist (No such file or directory)
```

I am using the last binary 1.23;

**Comment by marhop** [comment]
Hi,

sorry for the bad experience! I'm not familiar with nixos, but the error message looks like pandoc not finding the pandoc-unicode-math binary. If this is the case two reasons come to mind:

1. The pandoc-unicode-math binary is not in your PATH, so pandoc can't locate it at all, or
2. the pandoc-unicode-math binary is in your PATH, but it is not executable, so pandoc can't run it.

The binaries in the ZIPs from the [releases page](https://github.com/marhop/pandoc-unicode-math/releases) are not executable (this is an issue with the GitHub Actions CI process IIRC), so you would have to run something like `chmod u+x pandoc-unicode-math` on them first (nixos is Unix-like, right?).

Let me know if that works!

Cheers,
Martin

**Comment by YievCkim** [comment]
Hi thank you for your reply,

I did that: chmod the binary and put it in the PATH. I had an error about this but it's not the same.

Here the error looks like an issue with a syscall.

I think it tries to run a subprocess in order to run your plugin into. 

on second thought, I think it must be from pandoc on this OS (libc is not linked in the same way as other os).

If you're ok I can close this issue. Let me know.

**Comment by marhop** [comment]
Yes, I suppose that createProcess call is pandoc trying to run the pandoc-unicode-math filter, but unfortunately I don't know anything about nixos, so ... feel free to close the issue, and good luck!
