### ISSUE TITLE
Enhancement: add whitespace

### ISSUE THREAD

**Issue by fynnlyte** [marhop/pandoc-unicode-math#6]
The plugin works great so far with xelatex and my Unicode input via [Neo2](https://en.wikipedia.org/wiki/Neo_(keyboard_layout)). However, it requires some discipline that is not needed when working directly with xelatex, e.g. when typing:
```
$$
λe^{-λx}
$$
```
the output won't compile as it generates:
```
$$
\lambdae^{-\lamdbax}
$$
```
I'd suggest adding a whitespace after each replaced unicode symbol if it is followed by another letter / not followed by a whitespace or control symbol.

**Comment by marhop** [comment]
Good point! I'll see to this.

**Comment by marhop** [comment]
This feature is included in [release 1.2.0](https://github.com/marhop/pandoc-unicode-math/releases/tag/v1.2.0). Let me know if you encounter any problems!
