### ISSUE TITLE
Confusion around Ω and Ω

### ISSUE THREAD

**Issue by pilattebe** [marhop/pandoc-unicode-math#9]
## Expected behavior

- Ω should be translated to `\Omega`
- Ω should be translated to `\si{\ohm}` BUT it would require the \usepackage{siunitx} package

## Actual behavior

When outputting a pdf:

- Ω `OHM SIGN` is translated to  `\Omega` then to Ω `GREEK CAPITAL LETTER OMEGA`, which is wrong but acceptable.
- But Ω `GREEK CAPITAL LETTER OMEGA` is not translated to  \Omega then to Ω `GREEK CAPITAL LETTER OMEGA`, which is bad because it makes pandoc compilation fail.

## Solution

I propose that we do not use `\si{\ohm}` to avoid unnecessary dependencies and that we instead map everything to `\Omega` Ω `GREEK CAPITAL LETTER OMEGA`.

## Caveats

This will mean multiple characters map to one so the conversion will be lossy, so converting backward will be impossible for Ω `OHM SIGN`.

**Comment by pilattebe** [comment]
Oh, looks like GitHub (or my browser) is automagically converting U+2126 to U+03A9

**Comment by pilattebe** [comment]
BTW, the reason this is important to me is that alt+z (on QWERTY) makes a Ω and it's really convenient.

**Comment by pilattebe** [comment]
Please approve PR #10 to fix this issue

**Comment by marhop** [comment]
Well ... superficially mapping `OHM SIGN` to `\Omega` sounds wrong because of semantics. However, I tend to agree with you for the following reasons:

* As you hinted at, Pandoc's default Latex template does not depend on the siunitx package, so mapping to `\si{\ohm}` would crash without a custom template.
* Yes, converting backward is impossible. But that's not worse than Latex's very own handling of some Greek letters in math environments (e.g., `GREEK CAPITAL LETTER ALPHA` not being encoded as `\Alpha` but simply as `LATIN CAPITAL LETTER A`). Not exactly a design highlight ...
* According to [Wikipedia](https://en.wikipedia.org/w/index.php?title=Ohm&oldid=998035041), "Unicode encodes the symbol as U+2126 Ω OHM SIGN, [...] but it is only included for backwards compatibility and the Greek uppercase omega character U+03A9 Ω GREEK CAPITAL LETTER OMEGA [...] is preferred."

**Comment by pilattebe** [comment]
I have a mixed feeling relationship with unicode 😄.

Thank you for the feedback and info. 

> Unicode encodes the symbol as U+2126 Ω OHM SIGN, [...] but it is only included for backwards compatibility and the Greek uppercase omega character U+03A9 Ω GREEK CAPITAL LETTER OMEGA [...] is preferred.

This explains why I was unable to type it into GitHub, somebody somewhere has already tried to fix this mess.

**Comment by pilattebe** [comment]
@marhop How does the the backward conversion (Latex->Unicode) handles the mapping since there are two possibilities in that direction. We should make sure it doesn't put  U+2126 everywhere. (I can't test this right now, my computer is in repair)

**Comment by marhop** [comment]
Just FYI, the actual behavior you describe sounds like something got messed up.

>  * Ω `OHM SIGN` is translated to  `\Omega` then to Ω `GREEK CAPITAL LETTER OMEGA`, which is wrong but acceptable.

That's what happens after your PR, but before that `OHM SIGN` was not translated at all. Maybe you used the character outside a math environment together with `--pdf-engine=xelatex` (and a suitable font)?

>  * But Ω `GREEK CAPITAL LETTER OMEGA` is not translated to  \Omega then to Ω `GREEK CAPITAL LETTER OMEGA`, which is bad because it makes pandoc compilation fail.

Did you get an error message like this? If yes, this sounds very much like using Ω outside a math environment. This filter applies translations *only* inside math environments.

```
Error producing PDF.
! Package inputenc Error: Unicode character Ω (U+03A9)
(inputenc)                not set up for use with LaTeX.
```

**Comment by marhop** [comment]
> @marhop How does the the backward conversion (Latex->Unicode) handles the mapping since there are two possibilities in that direction. We should make sure it doesn't put U+2126 everywhere. (I can't test this right now, my computer is in repair)

Ouch, good catch! I always forget the backward thing ... I'll take a look. Guess it depends on the order of entries in the list.

**Comment by pilattebe** [comment]
> Just FYI, the actual behavior you describe sounds like something got messed up.

Yes ! You can totally dismiss the initial message, there were three errors in one (but only one had to do with your repo).

And to add to the confusion, for some reason pdflatex accepts the `OHM` but not the `OMEGA`.

**Comment by pilattebe** [comment]
> > @marhop How does the the backward conversion (Latex->Unicode) handles the mapping since there are two possibilities in that direction. We should make sure it doesn't put U+2126 everywhere. (I can't test this right now, my computer is in repair)
> 
> Ouch, good catch! I always forget the backward thing ... I'll take a look. Guess it depends on the order of entries in the list.

Wait... Does that mean every if I do Unicode to Latex to Unicode, I get the following ?
`LATIN A` -> `LATIN A` -> `GREEK LETTER A`

**Comment by marhop** [comment]
> > @marhop How does the the backward conversion (Latex->Unicode) handles the mapping since there are two possibilities in that direction. We should make sure it doesn't put U+2126 everywhere. (I can't test this right now, my computer is in repair)
> 
> Ouch, good catch! I always forget the backward thing ... I'll take a look. Guess it depends on the order of entries in the list.

Yes, it depends on the list order, which you intuitively did right. ;-) I added a comment in the file to make sure nobody changes this (see ff1ba848f0ad8555380ea30efe9dc6945b9c7262).

**Comment by pilattebe** [comment]
> Wait... Does that mean every if I do Unicode to Latex to Unicode, I get the following ?
> LATIN A -> LATIN A -> GREEK LETTER A

One possible fix for the thing above is to put `LATIN A -> LATIN A` at the top of the list

It will prevent **every** `LATIN A` from being colonized by Alexander the Great.

**Comment by marhop** [comment]
> Wait... Does that mean every if I do Unicode to Latex to Unicode, I get the following ?
> `LATIN A` -> `LATIN A` -> `GREEK LETTER A`

No. The backward translation does not touch ambiguous stuff like this. (Basically it ignores everything that does not start with `\`.) But on the flip side you get `GREEK A` -> `LATIN A` -> `LATIN A`, so roundtripping is generally not possible.

**Comment by pilattebe** [comment]
> > Wait... Does that mean every if I do Unicode to Latex to Unicode, I get the following ?
> > `LATIN A` -> `LATIN A` -> `GREEK LETTER A`
> 
> No. The backward translation does not touch ambiguous stuff like this. (Basically it ignores everything that does not start with `\`.) But on the flip side you get `GREEK A` -> `LATIN A` -> `LATIN A`, so roundtripping is generally not possible.

Ok great, keep in mind my hack in case you need to use it in the future 😄
